name: task_manager_and_weather
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.7 #for clean arch
  json_annotation: ^4.8.1 #for api json response
  bloc: ^8.1.2
  freezed_annotation: ^2.4.1 #fast and simple code generator ( copyWith methods )
  flutter_bloc: ^8.1.3
  dio: ^5.4.0 #HTTP networking package
  realm: ^1.7.0 #secure local db
  flutter_secure_storage: ^9.0.0 # secure storage for db key
  shared_preferences: ^2.2.2 # in app storage better with flutter_secure_storage



dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.6 #code generators
  json_serializable: ^6.6.2


flutter:

  uses-material-design: true
